version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddb-api
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: ddb2-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t  # Define a senha do usuário root
      MYSQL_DATABASE: ddb  # Cria um banco de dados padrão chamado "ddb"
      MYSQL_USER: ddbApi  # Define um usuário personalizado
      MYSQL_PASSWORD: abcdefg  # Define a senha do usuário personalizado
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
